### ISSUE TITLE
Neither mode-line nor notify work, if invoked with shell != bash

### ISSUE THREAD

**Issue by martin5233** [iqbalansari/mu4e-alert#10]
I tried out your package and could not get it to work at all on my machine. After some debugging, I found out, that this is due to the fact, that you add "2>/dev/null" to the command lines before invoking. This works without problems if the SHELL environment variable is set to bash, but not e.g. for tcsh.

**Comment by iqbalansari** [comment]
Thanks for the bug report. I guess this can be solved by explicitly calling out `bash` or maybe even better just using `/bin/sh`. What do you think?

**Comment by martin5233** [comment]
Thanks for your quick reply. I think it would probably be best, to use 
/bin/sh.

Best Regards,

Martin

**Comment by iqbalansari** [comment]
I have pushed a fix on master to use `sh`, please test it once MELPA updates and report back

Thanks

**Comment by martin5233** [comment]
Thanks for the quick fix. As I use el-get, I have tried it out immediately and it works without problems.

Thanks a lot,

Martin

**Comment by iqbalansari** [comment]
Great, thanks for confirming!
