### ISSUE TITLE
integrate with 'powerline'

### ISSUE THREAD

**Issue by srustamo** [iqbalansari/mu4e-alert#11]
Any easy way to integrate `'mu4e-alert-enable-mode-line-display` with [powerline](https://github.com/milkypostman/powerline)?

**Comment by iqbalansari** [comment]
I do not use `powerline` so I might not be able to provide a complete solution. I guess the only option you have is to define custom `powerline` theme. You can use `(powerline-raw mu4e-alert-mode-line)` to add modeline indicator at the desired position.

**Comment by srustamo** [comment]
Thank you. Let me try what you suggest.

**Comment by iqbalansari** [comment]
You are welcome. Please feel free to ask if you face any difficulty while creating the theme, I will try my best to help you

**Comment by thaaophz** [comment]
Have you get it to work?
Would be great if you could share your solution.

**Comment by iqbalansari** [comment]
@thaaophz [TheBB/spaceline](https://github.com/TheBB/spaceline) has some support for `mu4e-alert`, introduced here [here](https://github.com/TheBB/spaceline/pull/51). Not sure how well it works since I personally do not use spaceline/powerline.
