### ISSUE TITLE
Allow to only show interesting email after last run

### ISSUE THREAD

**Issue by lbolla** [iqbalansari/mu4e-alert#12]
It'd be useful to get notified only of new "interesting" emails arrived after last notification.
In other words, it'd be nice if one could set `mu4e-alert-interesting-mail-query` to be something like:
`mu find flag:new and not flag:trashed and date:<lastrun>..99991231`, where `<lastrun>` is a timestamp set after each notifcation.

EDIT: one can actually omit the last date in the query, like `mu find flag:new and not flag:trashed and date:<lastrun>..`, which is cleaner.

**Comment by iqbalansari** [comment]
Sounds like a good idea. Do you think it is worthwhile to make this the only behavior? Otherwise I can introduce a customization to allow users to switch between the current and the proposed behavior.

**Comment by lbolla** [comment]
I would allow `mu4e-alert-interesting-mail-query` to be either a string (legacy behaviour) or a function that returns a string, so that users can configure it as they please. Also, `<lastrun>` should be set in order to allow the specific behaviour I am interested in!

EDIT: the only doubt is what to do when one clicks on the little mail icon in the modeline. At the moment it shows whatever the notification does. Maybe in this case showing all unread emails would be best.

**Comment by iqbalansari** [comment]
I have pushed some changes to latest master to do achieve what you have described above.

I have taken a different approach to solving this, as you figured out in the last comment the same query is used to fetch the count of unread emails as well as to show the notification. As such customizing `mu4e-alert-interesting-mail-query` to include last run would be somewhat tricky. Instead I maintain the set of emails for which notifications have been show and exclude them from the notification generating process. This is the default behavior for now.

I have added a customization [option](https://github.com/iqbalansari/mu4e-alert#customizing-the-notifications-for-unread-emails-subjects) `mu4e-alert-notify-repeated-mails` to allow customizing this behavior.

Please do test when MELPA builds and report back. 

Thanks

**Comment by lbolla** [comment]
I think there is a bug (at least when using my version of `mu` 0.9.15) in that the "seen messages" hash table is keyed by `plist mail :id`, but it should actually be `plist mail :docid`.

This is the output from `mu`, for me.

lbolla@albion ~ > mu find -o sexp flag:unread
(
    :docid 41137
    :subject "Yadda yadda yadda"
    :from ...
    :to ...
        :message-id "1276071968.229301455525749512.JavaMail.root@c18ccfb2ab6a"
    :date (22209 36725 0)
    :size 34496
        ...
)

I am ensure if, instead of `docid`, `message-id` should be used.

**Comment by iqbalansari** [comment]
You are right, actually I coded up that part in a hurry I should have been more careful :disappointed:. 

> I am ensure if, instead of docid, message-id should be used.

I think either should be good, `mu4e` itself [uses](https://github.com/djcb/mu/blob/ac0b1b755a78417b96b3d92f5d160a8a6ebc9271/mu4e/mu4e-headers.el#L1419) `:docid` though so I have chosen to use it

**Comment by lbolla** [comment]
Looking good, thanks!
