### ISSUE TITLE
Cyclic notification

### ISSUE THREAD

**Issue by MaksVal** [iqbalansari/mu4e-alert#15]
Hi! 
Thanks for you plugins!
It's working now, but it have a some problem with my emacs-server.

I use emacs server and your notification does work how I start server. But it doesn't work, if my emacs doesn't restart.

How I can use periodic notification?
Thanks!

**Comment by iqbalansari** [comment]
Hi,

I am not really sure I understood the problem. Do you mean that you stop getting notifications after restarting the server? 

Thanks

**Comment by MaksVal** [comment]
Hi!
I get notifications only once, when I run the  emacs . And that's all. If I will restart my emacs, I will get notification.

**Comment by iqbalansari** [comment]
Earlier notifications were shown for each unread email, irrespective of whether user has been notified for the email before, `mu4e-alert` was updated recently to not display such duplicate notifications. So if you do not get any new emails you will not get any new notifications. If you prefer the old behavior [configure](https://github.com/iqbalansari/mu4e-alert/blob/6a724e8457fc9e4d2a9464f06316253e04048bd4/mu4e-alert.el#L137-L146) the variable `mu4e-alert-notify-repeated-mails`

``` elisp
(setq mu4e-alert-notify-repeated-mails t)
```

Thanks

**Comment by iqbalansari** [comment]
Hi @MaksVal,

I assuming your problem is resolved and closing this, feel free to open if the issue persists

Thanks

**Comment by MaksVal** [comment]
@iqbalansari  please forgive me for my very long reaction!

Your notification is working fine, if I start a one instance of emacs.
If I start up emacs as is server then I don't get notification.
I tried to set the next variables:
                  - (setq mu4e-alert-notify-repeated-mails t)
                  - (mu4e-alert-set-default-style 'libnotify)

How can I enable a debug mode for your plugin?

Thanks!!!

**Comment by iqbalansari** [comment]
Hi @MaksVal ,

No worries, I thought you had resolved the issue.

I tried running `mu4e-alert` from Emacs daemon and it seems to work fine. Are you starting the Emacs daemon from a terminal in which case do you see any error in the logs?

Also can you run the following piece of code in `ielm` (you can start the it by doing <kbd>M-x</kbd>`ielm`<kbd>RET</kbd>) and report what do you see, it should print a message of the form "Got <n> mails" (make sure you mark some mails as unread before running it).

```emacs-lisp
(mu4e-alert--get-mu-unread-mails (lambda (mails) (message "Got %d mails" (length mails))))
```

**Comment by iqbalansari** [comment]
Hi @MaksVal,

Did you get a chance to try out the things I mentioned in the previous message?

**Comment by MaksVal** [comment]
Hi @iqbalansari!

Sorry. Yes of course!

```
ELISP> (mu4e-alert--get-mu-unread-mails (lambda (mails) (message "Got %d mails" (length mails))))
(closure
 ((callback lambda
            (mails)
            (message "Got %d mails"
                     (length mails)))
  t)
 (process _)
 (if
     (equal
      (process-status process)
      'exit)
     (progn
       (cond
        ((= 0
            (process-exit-status process))
         (funcall callback
                  (mu4e-alert--parse-mails
                   (process-buffer process))))
        ((=
          (process-exit-status process)
          4)
         (funcall callback nil)))))
 (if
     (memql
      (process-status process)
      '(exit signal))
     (progn
       (kill-buffer
        (process-buffer process)))))
```

I have a one unread message. My problem still exists. I don't get notification if the emacs as daemon.

**Comment by iqbalansari** [comment]
Hmm... it seems to be working on my side. Would it be possible for you to post your Emacs configuration? Also please post you OS and Emacs version and `mu4e` version

**Comment by iqbalansari** [comment]
Also would you mind if we continue the discussion on email?

**Comment by MaksVal** [comment]
Yes, of course. Please, give me a two days. Thanks you!

9 марта 2017 г. 9:30 PM пользователь "Iqbal Ansari" <
notifications@github.com> написал:

Also would you mind if we continue the discussion on email?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iqbalansari/mu4e-alert/issues/15#issuecomment-285438176>,
or mute the thread

**Comment by MaksVal** [comment]
Together  we have found a reason this problem. My emacs running as is a daemon the systemd service. It didn't know   about any environments(DISPLAY and DBUS_SESSION_BUS_ADDRESS). I imported this variable.
