### ISSUE TITLE
multiple emacs/mu4e instances

### ISSUE THREAD

**Issue by defanor** [iqbalansari/mu4e-alert#16]
When invoking mu4e from different emacs instances, using different
contexts, maildirs (`mu4e-maildir`), and mu databases
(`mu4e-mu-home`), apparently setting
`mu4e-alert-enable-mode-line-display` on `after-init-hook` leads to
mu4e-alert using the default `mu4e-mu-home` even on secondary emacs
instances, while with `mu4e-main-mode-hook` the mode line
notifications don't get shown. Setting both seems to do the trick, but
that's quite confusing. Would be nice to fix it somehow, and/or to
write down the instructions.

mu4e 0.9.16, emacs 24.5.1, mu4e-alert 20160215.209 from melpa.

**Comment by iqbalansari** [comment]
Hi,

Thanks for the bug report. Unfortunately I am not able to reproduce this behavior. `mu4e-alert` does not do anything fancy with `mu4e-mu-home` variable, it simply passes it to `mu` while invoking it, so I am not  sure why this would happen. How did you check that `mu4e-alert` is using the default `mu4e-mu-home`? If you are familiar with edebug, may I ask you to debug the function `mu4e-alert--get-mu-unread-mails` and see if it is using the correct value for `mu4e-mu-home`?

**Comment by defanor** [comment]
Not recalling how I've checked that `mu4e-mu-home` is not set, maybe
didn't check it properly or during evaluation.

`mu4e-mu-home` is default during `after-init-hook` because it is not set
here when `after-init-hook` is fired: I'm setting `mu4e-mu-home` and
`mu4e-user-mail-address-list` per-context (via `:vars`), so that I can
pick different contexts in different instances, and they won't lock the
same database.

I've reproduced the behaviour once again, by commenting those hooks out:
- When using `after-init-hook` alone, and checking with `edebug-defun`
  on `mu4e-alert--get-mu-unread-mails`, `mu4e-mu-home` appears to be
  correct during its evaluation, but there's no alert (probably that's the
  case where it would be there if I had unread messages in another
  context).
- When using `mu4e-main-mode-hook` alone,
  `mu4e-alert--get-mu-unread-mails` doesn't run – that's the case when
  not seeing any notifications at all.
- When using both, a notification is there, as it should be.

So, it looks like mu4e-alert uses the default database when using
`after-init-hook` alone. Is it possible that it captures/stores
`mu4e-mu-home` value on `mu4e-alert-enable-mode-line-display` invocation
somehow? That assumption made me to try both hooks at once, and then it
worked.

**Comment by defanor** [comment]
Checked with `after-init-hook` and unread messages in another context:
mmu4e-alert showed a notification before mu4e invocation, but didn't
show after it. And seemed to work properly then: even shows
notifications when there are unread messages in the active
context. Though that's quite strange, for I think I've checked it just
before, and it didn't work.

**Comment by defanor** [comment]
Here it is again: with `after-init-hook` alone, after invoking emacs
while there's a single unread message in the context that uses the
default mu home and maildir, there was a notification. After invoking
mu4e and checking for new letters (`U`), it didn't go away, though it
already was read in that context (that is, I see a notification, but
there's no unread messages in any of my mailboxes).

`mu4e-alert--get-mu-unread-mails` seems to only run when receiving new
mail (not when just checking it), `mu4e-mu-home` seems to be set
correctly there, but after reading that mail, I still see a
notification. After sending two more letters to myself, the notification
says that there is 2 unread letters, it decreases after reading one of
them, and vanishes once the other one is read.

So it looks like mu4e-alert brings some state from the default context,
and then gets rid of that occasionally.

**Comment by iqbalansari** [comment]
Hi, 

I cannot think of what could be causing this issue, could you please post your entire mu4e and mu4e-alert config? Another way for you try debugging this issue is to try something like the following in `ielm` (before and after changing `mu4e-context`)

``` emacs-lisp
(mu4e-alert--get-mu-unread-mails (lambda (m)
                                  (setq mails m)))
```

After the above form completes execution the variable mails should be set to the unread mails that `mu4e-alert` could retrieve (technically since the mails are fetched asyncronously the above is inaccurate)

Another you could try is to set `mu4e-alert-repeated-mails` to an empty hash table after changing context (you can use the following `(ht-create #'equal)`)

Thanks

**Comment by iqbalansari** [comment]
Also sorry for the late reply was quite last few weeks

**Comment by defanor** [comment]
My current configuration (with private bits removed):

mu-mail.el:

```
(require 'mu4e)
(require 'smtpmail)

;; mu4e-alert
(add-hook 'mu4e-main-mode-hook #'mu4e-alert-enable-mode-line-display)
(add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display)

(setq mu4e-html2text-command "w3m -dump -T text/html"
      mu4e-compose-pre-hook 'mu4e~request-contacts
      ;; mu4e-refile-folder settings here
      )
```

private.el.gpg:

```
(setq mu4e-contexts
      `( ,(make-mu4e-context
           :name "private"
           :enter-func (lambda ()
                         (mu4e-message "Switch to the Private context")
                         )
           :leave-func (lambda () (mu4e-clear-caches))
           :match-func (lambda (msg)
                         (when msg
                           (mu4e-message-contact-field-matches
                            msg
                            :to "user@host")))
           :vars '( (user-mail-address            . "user@host")
                    (user-full-name               . "user")
                    (smtpmail-default-smtp-server . "host")
                    (smtpmail-local-domain        . "host")
                    (smtpmail-smtp-user           . "user")
                    (smtpmail-smtp-server         . "host")
                    (smtpmail-stream-type         . ssl)
                    (smtpmail-smtp-service        . 465)
                    (mu4e-get-mail-command        . "mbsync -q host")
                    (mu4e-update-interval         . 300)
                    (mu4e-view-show-addresses     . t)
                    (mu4e-maildir                 . "~/Maildir")
                    (mu4e-mu-home                 . "~/.mu")
                    (mu4e-user-mail-address-list  . ("user@host"))
                    ))
         ;; 3 more contexts here, 2 with different maildir and mu-home
         ))
```

Unfortunately, I'm also not quite up to debugging right now, but probably will try later.

**Comment by iqbalansari** [comment]
``` emacs-lisp
(add-hook 'mu4e-main-mode-hook #'mu4e-alert-enable-mode-line-display)
(add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display)
```

You do not seem to enabling desktop notifications, you can add the following to the init file to [enable notifications](https://github.com/iqbalansari/mu4e-alert#desktop-notifications-for-unread-emails)

``` emacs-lisp
(add-hook 'after-init-hook #'mu4e-alert-enable-notifications)
```

Secondly the `mu4e-contexts` [documentation](https://www.djcbsoftware.nl/code/mu/mu4e/Contexts-example.html) says that `mu4e-maildir` and `mu4e-mu-home` cannot be changed without restarting `mu4e`

> You can set any kind of variable; including settings for mail servers etc. However, settings such as mu4e-maildir and mu4e-mu-home are not changeable after they have been set without quitting mu4e first. 

But I guess that is relevant only for `mu4e` application and should not affect `mu4e-alert` since we use the program `mu` directly. Once you get sometime to debug can you also post the output of the following

``` emacs-lisp
(s-join " "
        (append (mapcar #'shell-quote-argument
                        (append (list mu4e-mu-binary
                                      "find"
                                      "--nocolor"
                                      "-o"
                                      "sexp"
                                      "--sortfield=d"
                                      (format "--maxnum=%d" mu4e-alert-max-messages-to-process))
                                (when mu4e-headers-skip-duplicates
                                  (list "-u"))
                                (when mu4e-mu-home
                                  (list (concat "--muhome=" mu4e-mu-home)))
                                (split-string mu4e-alert-interesting-mail-query)))))
```

**Comment by defanor** [comment]
I don't want desktop notifications (just mode-line), and using
different mu-homes from different emacs instances, without switching
between them (yet it seems that in the very beginning, before choosing
a context, it grabs the number of unread messages from the default
one, `.mu`).

Here is the output of that from one instance:

```
"/usr/local/bin/mu find --nocolor -o sexp --sortfield\\=d --maxnum\\=500 --muhome\\=\\~/.mu flag\\:unread AND NOT flag\\:trashed"
```

And from another:

```
"/usr/local/bin/mu find --nocolor -o sexp --sortfield\\=d --maxnum\\=500 --muhome\\=\\~/.mu-work flag\\:unread AND NOT flag\\:trashed"
```

But that's when they work fine. Will try to get it broken and gather
more information soon.

**Comment by defanor** [comment]
Here it is, before even starting mu4e, with my regular configuration:

```
"/usr/local/bin/mu find --nocolor -o sexp --sortfield\\=d --maxnum\\=500 flag\\:unread AND NOT flag\\:trashed"
```

And `mu4e-alert--get-mu-unread-mails` shows the test mail I have in `.mu`. Without `mu4e-main-mode-hook`, it doesn't go away after choosing a work context (that uses `.mu-work`), while does otherwise. Also, without that hook, after choosing a context:

```
"/usr/local/bin/mu find --nocolor -o sexp --sortfield\\=d --maxnum\\=500 --muhome\\=\\~/.mu-work flag\\:unread AND NOT flag\\:trashed"
```

And `mu4e-alert--get-mu-unread-mails` sets `mails` to `nil`, while there's a notification about one letter.

**Comment by defanor** [comment]
Oh, and while there is that false notification and a "work" context is chosen, `mu4e-alert-repeated-mails` is set to an empty hash.

**Comment by iqbalansari** [comment]
> And mu4e-alert--get-mu-unread-mails sets mails to nil, while there's a notification about one letter.

Sorry for the confusion, I thought you were talking about desktop notifications, this variable is irrelevant if you do not want those.

I think I get the problem now, so basically you start Emacs with default `mu4e` configuration, `mu4e-alert` then shows whatever emails you have from the default `mu-home` in the mode-line. However the mode-line does not update itself even after you switch the contexts. Am I understanding your problem correctly? Also the modeline must be updating itself after you update the emails (either manually or via `mu4e` automated update mechanism), is that correct?

Thanks

**Comment by defanor** [comment]
> I think I get the problem now, so basically you start Emacs with
> default `mu4e` configuration, `mu4e-alert` then shows whatever emails
> you have from the default `mu-home` in the mode-line. However the
> mode-line does not update itself even after you switch the
> contexts. Am I understanding your problem correctly?

Yes. Though I don't exactly switch contexts -- rather, choosing one when
starting mu4e.

> Also the modeline must be updating itself after you update the emails
> (either manually or via `mu4e` automated update mechanism), is that
> correct?

That's the expected behaviour, yes. Also when choosing a context.

Currently it seems to do that on update only if new letters are received
during it.

I think it's not critical that the default `mu-home` is used before a
context is chosen, but it's confusing when there's that false alert
after that.

**Comment by iqbalansari** [comment]
> That's the expected behaviour, yes. Also when choosing a context.

Sorry I was a bit unclear, I meant currently the modeline updates itself after you update the emails, right?

> Yes. Though I don't exactly switch contexts -- rather, choosing one when starting mu4e.

I am assuming you are choosing the context using `mu4e-context-switch`, am I right? In which case fix would be a trivial advice around `mu4e-context-switch` to update the modeline, let me try pushing it tonight

**Comment by defanor** [comment]
> Sorry I was a bit clear, I meant currently the modeline updates itself
> after you update the emails, right?

Oh. Well, as wrote above, currently it only does that if new letters
were received on update -- that is, it doesn't update if I press `U`,
but there is no new letters in the selected context/mailbox.

> I am assuming you are choosing the context using
> `mu4e-context-switch`, am I right? In which case fix would be a
> trivial advice around `mu4e-context-switch` to update the modeline,
> let me try pushing it tonight

Yes, apparently. I'm choosing it by running mu4e and selecting a context
by entering the first letter of its name, what seems to be implemented
in `mu4e-context-determine`, which is called from
`mu4e~context-autoswitch`, which uses `mu4e-context-switch`.

**Comment by iqbalansari** [comment]
I have [pushed](https://github.com/iqbalansari/mu4e-alert/commit/3af4808b2c8bfac7882a727f32d0fc4bc20cb821) a commit to master, to update the count on mode-line after a context switch, hopefully this would solve your problem

Thanks

**Comment by defanor** [comment]
Thanks, works fine now.
