### ISSUE TITLE
" *mu4e-mails*" buffers

### ISSUE THREAD

**Issue by defanor** [iqbalansari/mu4e-alert#18]
Apparently mu4e-alert creates a lot of `" *mu4e-mails*"` buffers, and their amount only grows with time, leading to lags with some other modes that work with buffers. Perhaps `mu4e-alert--get-mail-sentinel` or `mu4e-alert--parse-mails` should close those buffers once the parsing is done.

**Comment by defanor** [comment]
I'm currently using this, appears to work:

```
(defun mu4e-alert--get-mail-sentinel (callback)
  "Create sentinel for process to get mails from mu, CALLBACK is called with the unread mails."
  (lambda (process _)
    (when (memql (process-status process) '(exit signal))
      (funcall callback (mu4e-alert--parse-mails (process-buffer process)))
      (kill-buffer (process-buffer process)))))
```

**Comment by iqbalansari** [comment]
Hi,

Thanks for the heads up. Something like you posted should work, wish to create a pull request?

**Comment by defanor** [comment]
Yup, will create it now.
