### ISSUE TITLE
Does it works with MacOS X?

### ISSUE THREAD

**Issue by zilongshanren** [iqbalansari/mu4e-alert#2]
I noticed that the screenshot is made under Linux, would it be possible to support MacOS X?
Thanks.

**Comment by iqbalansari** [comment]
It should be easy to make it work on MacOS X. Unfortunately I do not have access to a MacOS X machine, so I might not be able to provide a 'ready-to-use' snippet. 

`mu4e-alert` uses [alert](https://github.com/jwiegley/alert) to show desktop notifications, which supports a variety of [styles](https://github.com/jwiegley/alert#builtin-alert-styles). You need to configure `mu4e-alert` to use a style that works on your system. 

Looking at alert's documentation it seems `growl` and `notifier` style should work on MacOS X. So if you have [terminal-notifier](https://github.com/julienXX/terminal-notifier) installed, add something like the following to your init file to enable notifications using `terminal-notifier`

``` elisp
(mu4e-alert-set-default-style 'notifier)
```

Alternately if you have [growl](http://growl.info/) installed you can instruct `mu4e-alert` to use it by doing the following

``` elisp
(mu4e-alert-set-default-style 'growl)
```

Please try the above and report back if works (or even if it does not work)

Hope the above helps!

**Comment by iqbalansari** [comment]
@zilongshanren Hi, just wanted to know if any of the above methods worked for you

**Comment by iqbalansari** [comment]
Oops! I think I closed this by mistake

**Comment by justmytwospence** [comment]
That method works for moi

**Comment by iqbalansari** [comment]
Great! I guess I will update the README with instructions for OSX and close this issue. Thanks @justmytwospence

**Comment by zilongshanren** [comment]
@iqbalansari 
Thanks, I will test it on my MacOS X.

**Comment by iqbalansari** [comment]
Closing this, I have added some [instructions](https://github.com/iqbalansari/mu4e-alert#getting-desktop-notifications) for enabling desktop notifications. to the README. Feel free to reopen if you face any issues or feel the documentation is not clear.

Thanks

**Comment by jkbellew** [comment]
Hi. I have installed terminal-notifier on OS X and I still can't get the alerts. My .emacs file has the following lines: 

`(mu4e-alert-set-default-style 'notifier)`
`(add-hook 'after-init-hook #'mu4e-alert-enable-notifications)`
`(add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display)`

And it doesn't seem to call terminal-notifier (same issue with growl). I have verified that the notifier works and there should be no issue. I do see the mode line updated but that is all.

Thanks in advance.

**Comment by iqbalansari** [comment]
Most probably this is because Emacs cannot find `terminal-notifier` binary. What is the output of <kbd>M-:</kbd>`(executable-find "terminal-notifier")`<kbd>RET</kbd>? Also could you please post the value of the variable `alert-notifier-command`?

**Comment by jkbellew** [comment]
Things that I need to check. I verified that the binary was in my path but it is not found by Emacs. And there is no value for `alert-notifier-command` it states `Symbol' s function definition is void: alert-notifier-command`. 

I'll go ahead and make sure that the binary is found and try again. The rest of this works pretty well, as the mode line shows me when I have mail.

**Comment by iqbalansari** [comment]
> I verified that the binary was in my path but it is not found by Emacs.

That explains the lack of notifications. For testing quickly you can manually set `alert-notifier-command` to the full path to `terminal-notifier` and try again. In general I think [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) would be useful if you Emacs to see the same PATH as your shell

**Comment by jkbellew** [comment]
I will have to check the exec path to make sure it is finding it.

I'll let you know.

Jason K Bellew
@theshaggyviking

**Comment by jkbellew** [comment]
And it worked thanks. Once I set the command manually everything is coming up roses.
