### ISSUE TITLE
got an error about function "mu4e-alert--get-mu-unread-emails-internal"

### ISSUE THREAD

**Issue by SyrakuShaikh** [iqbalansari/mu4e-alert#22]
Spacemacs 0.200.7 Emacs 25.1.1 mu4e 0.9.18

I just updated the "mu4e-alert" package and ran into this error:

Error running timer ‘mu4e-alert--get-mu-unread-emails-internal’: (void-function mu4e-alert--get-mu-unread-emails-internal)

**Comment by iqbalansari** [comment]
Hi,

Thanks for bug report. I fixed this on master branch, which should be available in next couple of hours, really sorry for the breakage.

**Comment by SyrakuShaikh** [comment]
OK. Thanks for your quick fix.
