### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by Sbozzolo** [iqbalansari/mu4e-alert#25]
Hello,

I cannot get desktop notifications working properly. 
I am using Arch Linux, GNU Emacs 25.3.1 and EXWM 0.15 and dunst 1.2.0 as notification server.
I can correctly display notifications with this snippet:
```
(require 'alert)
(setq alert-default-style 'libnotify)
(alert "This is an alert")
````
Nonetheless, setting `libnotify` as default style and enable notifications don't produce any
notification when mu4e-update is executed. On the other hand, the modeline counter is
properly updated.

EDIT: 

I've read the previous issues and I included the important fix by jwiegley (https://github.com/jwiegley/alert/commit/80374afedc1b99c283ea2a66327fa2d52e43bdfd), which is still not in the alert library, so I had to patch manually the code. It doesn't change anything.

Best,
sbozzolo

**Comment by iqbalansari** [comment]
Hi @Sbozzolo,

Sorry for the late reply. This might need some debugging. What happens you execute the following code (for example in `ielm`)

```elisp
(require 'alert)
(alert "Debugging mu4e-alert" :title "mu4e-alert" :category "mu4e-alert")
```

Also could you please confirm that you are on the latest version of `alert` and `mu4e-alert`?

**Comment by Sbozzolo** [comment]
Hello,

If I execute the code I can see the notification as expected with dunst.

I am using alert 1.2 with the patch and mu4e-alert 1.0 from MELPA Stable. I have tried also the version from MELPA (20170901.1027), but the result is the same.

**Comment by iqbalansari** [comment]
OK, I guess for some reason the hooks are not being setup properly.

1) What is the value of the variable `mu4e-index-updated-hook`?

2) Could you run the following snippet in `ielm`, ideally it should display the count of unread notifications  

```lisp
(require 'mu4e-alert)
(mu4e-alert--get-mu-unread-mails (lambda (mails)
                                   (mu4e-alert-notify-unread-messages-count (length new-mails))))
```

**Comment by Sbozzolo** [comment]
Hello,

the value of `mu4e-index-updated-hook` is:
```elisp
(mu4e~headers-maybe-auto-update mu4e-alert-notify-unread-mail-async mu4e-alert-update-mail-count-modeline
                                (lambda nil
                                  (run-hooks 'mu4e-message-changed-hook)))
```

But output of your code is:
```elisp
[nil 23015 19805 599870 nil mu4e-alert--get-mu-unread-emails-1
     (mu4e-alert--email-processor)
     nil 827000]
```
Nonetheless, the icon in the modeline is correctly displaying that I have one non-read email.

**Comment by iqbalansari** [comment]
I am really sorry, I had a typo in the snippet

Could run the following instead

```lisp
(mu4e-alert--get-mu-unread-mails (lambda (mails)
                                   (mu4e-alert-notify-unread-messages-count (length mails))))
```

It should display a desktop notifications with the count of emails, if the above the does not work also run the following (also check the echo area it might log errors if any)

```lisp
(mu4e-alert--get-mu-unread-emails-1 (lambda (mails)
                                      (mu4e-alert-notify-unread-messages-count (length mails))))
```

**Comment by Sbozzolo** [comment]
Both the commands produce the desktop notification, and the output is:

1.
```elisp
[nil 23015 21221 770760 nil mu4e-alert--get-mu-unread-emails-1
     (mu4e-alert--email-processor)
     nil 526000]
```

2.
```elisp
#[514 "\301!\302\232\203'\303!\304U\203\300\305\306!!!\210\202'\303!\307U\203'\300\310!\210\311\301!\312\"\2055\313\306!!\207"
      [(lambda
         (mails)
         (mu4e-alert-notify-unread-messages-count
          (length mails)))
       process-status exit process-exit-status 0 mu4e-alert--parse-mails process-buffer 4 nil memql
       (exit signal)
       kill-buffer]
      6 "\n\n(fn PROCESS _)"]
```

**Comment by iqbalansari** [comment]
I think that the `mu4e-index-updated-hook` is not being run for some reason. You update the emails via `mu4e` right? What is the value the variable `mu4e-update-interval`?

**Comment by Sbozzolo** [comment]
I am updating the emails with `mu4e` with `mu4e-update-interval 300`. I have also tried to define a function which I run every minute with a timer:
```elisp
       (defun mu4e-alert--update-stats ()
         (interactive)
         (mu4e-update-mail-and-index t)
         (run-hooks 'mu4e-index-updated-hook)
       )
```
As you can see I am forcing to run the hooks, but even in this case I cannot see any notification produced with `mu4e-alert`.

**Comment by iqbalansari** [comment]
I am running out of ideas 😄 .

You do not get any notifications at all right? `mu4e-alert` displays the unread emails notifications whenever Emacs starts up, you do not those too? I am asking because by default `mu4e-alert` does not display notifications for emails that the user has been already notified of, so unless get fresh new emails no notifications would be displayed. To disable this try doing something like

```lisp
(setq mu4e-alert-notify-repeated-mails t)
```

Also could you confirm that running `(run-hooks 'mu4e-index-updated-hook)` does not work as well.

Finally would it be possible for you to post relevant bit of your Emacs configuration (even better a link to the complete configuration if it is on Github)

Thanks

**Comment by Sbozzolo** [comment]
Hello,

I don't get any notification at all and I can confirm that even running the hooks no new notification is displayed. Right now I am (slowly) transitioning to Gentoo. I won't exclude that on this new clean system everything will work. I will let you know what happens.

**Comment by ghost** [comment]
I'm experiencing the same problem using i3 and dunst on Arch.

When I execute `(alert "Debugging mu4e-alert" :title "mu4e-alert" :category "mu4e-alert")` I get a notification, but mu4e doesn't send notifications to dunst.

`(run-hooks 'mu4e-index-updated-hook)` outputs `nil`.

I also tried the other commands you asked for, but they output the same as they did for Sbozzolo.

**Comment by iqbalansari** [comment]
Hi @schaulus,

Thanks for the inputs, what happens when you execute the following

```lisp
(setq mu4e-alert-notify-repeated-mails t)
(mu4e-alert-notify-unread-mail-async)
```

**Comment by schaulus** [comment]
I get the following output in the minibuffer:
`[nil 23218 37742 830005 nil mu4e-alert--get-mu-unread-emails-1 (mu4e-alert--email-processor) nil 283000]`

**Comment by ghost** [comment]
I sent myself an e-mail and then executed the two lines. I get the following output in the minibuffer:
`[nil 23218 37955 534606 nil mu4e-alert--get-mu-unread-emails-1 (mu4e-alert--email-processor) nil 0]`

**Comment by iqbalansari** [comment]
@schaulus hmm, are you familiar with debugging Elisp?

**Comment by ghost** [comment]
@iqbalansari Unfortunately not...

**Comment by iqbalansari** [comment]
I just tried this on two system `i3` + `dunst` on Archlinux 2018.03.01 (running on VirtualBox) and `i3` + `dunst` on Ubuntu 16.04 and it worked correctly on both on them, so I am not really sure why it is not working on your system

**Comment by iqbalansari** [comment]
When you get a chance could you run `dbus-monitor path=/org/freedesktop/Notifications` (as suggested [here](https://github.com/dunst-project/dunst/issues/506#issuecomment-375288724)) before running the [`(mu4e-alert-notify-unread-mail-async)`](https://github.com/iqbalansari/mu4e-alert/issues/25#issuecomment-374659213) function. The `dbus-monitor` command should print the notification requests that `mu4e-alert` is sending to `dunst` (if any)

**Comment by elzorrorebelde** [comment]
I'm also an Arch Linux (running Gnome 3) user with this issue.  I can see the notification of unread email when emacs start but then my [imapnotify](https://gitlab.com/shackra/goimapnotify) application runs `emacsclient -eval '(mu4e-update-index)'` syncing the new email and no notifications appears despite the fact I have new email.

**Comment by iqbalansari** [comment]
Hello @shackra, I see you had opened an issue against `mu`, did the fix in `mu` work, can I close this issue

**Comment by elzorrorebelde** [comment]
Hey!
Yes, it seems to be working again, you can close this issue.
