### ISSUE TITLE
Define filter for messages to be notified about

### ISSUE THREAD

**Issue by andreas-h** [iqbalansari/mu4e-alert#30]
First of all thanks for this great library, it's really making working with mu4e so much fun :)

It would be great if there were a way to select which kind of messages (not) to be notified about.  For example, my mail server tags potential spam messages with `[SPAM]` in the subject line. It would be great to tell mu4e-alert that I don't want to be notified when such an email gets delivered to my maildir.

Is this somehow possible?

**Comment by iqbalansari** [comment]
Hi @andreas-h,

Sorry for the delay in the reply and thanks for the bug report. You can configure the kind of emails `mu4e-alert` considers for notifications by [customizing](https://github.com/iqbalansari/mu4e-alert#general-options) the variable `mu4e-alert-interesting-mail-query`. It accepts the mu4e search query, see mu4e [manual](https://www.djcbsoftware.nl/code/mu/mu4e/Queries.html) for details about the syntax. Let me know if that does not solve your problem.

Thanks

**Comment by iqbalansari** [comment]
@andreas-h I believe `mu4e-alert-interesting-mail-query` is what you need, closing this issue for now feel free to re-open if your issue is not yet resolved
