### ISSUE TITLE
Two notifications for every new email

### ISSUE THREAD

**Issue by tareefdev** [iqbalansari/mu4e-alert#32]
I installed the package from melpa, added the following to my init.el file:

    (mu4e-alert-set-default-style 'libnotify)
    (add-hook 'after-init-hook #'mu4e-alert-enable-notifications)
    (add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display)

After restarting emacs, I got two notifications for every new email

![screenshot_20180728_094342](https://user-images.githubusercontent.com/17391433/43353953-4869d3ee-924b-11e8-8224-a33037ad93ee.png)

**Comment by iqbalansari** [comment]
Hi @tareefdev,

These are two different types of notifications (please see the [README](https://github.com/iqbalansari/mu4e-alert#customizing-the-types-of-notifications-displayed) for more details). Basically by default, when new emails arrive `mu4e-alert` displays a notification with the total number of new emails, followed by subjects of the new emails. However you can configure it do just one of the two by configuring `mu4e-alert-email-notification-types`

- Set it to `'(count)` to just display the count of new emails
```elisp
(setq mu4e-alert-email-notification-types '(count))
```
- Set it to `'(subjects)` to just display the subjects of new emails
```elisp
(setq mu4e-alert-email-notification-types '(subjects))
```

Thanks

**Comment by tareefdev** [comment]
Oh! Sorry I didn't pay attention to that section, thanks for your fantastic package
