### ISSUE TITLE
category string vs symbol

### ISSUE THREAD

**Issue by seblemaguer** [iqbalansari/mu4e-alert#35]
Hello,

is there a specific reason why the category is a string and not a symbol? According to the document of the "alert" function, the category should be a symbol.

Thanks a lot

**Comment by iqbalansari** [comment]
Hello @seblemaguer, I do not remember the reason why I went with string instead of symbol. `alert` works with both symbol and string.

**Comment by seblemaguer** [comment]
thanks for the answer, I was using a symbol on one of my package which is mixing sauron and alert, I updated it to take also strings into account :)
