### ISSUE TITLE
pipe to notify-send the email subject and or sender?

### ISSUE THREAD

**Issue by zeltak** [iqbalansari/mu4e-alert#5]
Hi again!

just thought it would be cool if we could pipe to notify-send the email subject and or sender instead of the generic "you have mail" each time

best

Z

**Comment by iqbalansari** [comment]
That sounds like a useful feature. However I am not sure what the behaviour should be
- Should the sender/subject of all unread emails be notified to user? 
- Should all notifications be displayed separately or in one notification itself?

Perhaps we can restrict the number of subjects/sender shown to a minimum number (perhaps 5). What do you think?

**Comment by zeltak** [comment]
Hi again

i think restricting is the way to go, maybe the last 3-5 unread messages will be sent each time? 

would be very happy to test it (i cant code at all so will be useless on that front :))

best

z

**Comment by iqbalansari** [comment]
Hi, 

I have started working on this perhaps it will be ready by tomorrow. In case you want look at the code see [feature/subject-in-notifications](https://github.com/iqbalansari/mu4e-alert/tree/feature/subject-in-notifications) branch.

**Comment by zeltak** [comment]
cool, sounds great. i cant code for my life but ill be very happy to test it!

best

Z

**Comment by iqbalansari** [comment]
Just wanted to say I have not forgotten about this, I will ping you back when the code is ready.

**Comment by zeltak** [comment]
no worries :)

best

Z

zeltak

**Comment by iqbalansari** [comment]
Hi @zeltak,

Apologies for the delay. I have implemented this feature on [feature/subject-in-notifications](https://github.com/iqbalansari/mu4e-alert/tree/feature/subject-in-notifications) branch. Would you like to give it a try?

**Comment by zeltak** [comment]
Hi iqbalansari, no worries for the delay at all :)

sure id love to try (keep im mind im not very technical :))

best

Z

**Comment by iqbalansari** [comment]
OK I have prepared a pre-release package for you, download it (`mu4e-alert-20151206.0.tar`) from `Downloads` section [here](https://github.com/iqbalansari/mu4e-alert/releases/tag/0.2.1-pre). Then in your Emacs do <kbd>M-x</kbd>`package-install-file`<kbd>RET</kbd> and provide the path to the downloaded file, restart Emacs. Hopefully if all goes well you should have the latest version of `mu4e-alert`.

Now execute the command `mu4e-alert-enable-notifications`. The earlier notification with number of emails, should be followed by notifications showing the emails with subjects.

**Comment by iqbalansari** [comment]
Hi @zeltak, did you get a chance to try this out?

**Comment by zeltak** [comment]
Hi iqbal

not yet, was swamped with teaching today. will try to try it out tonight

thx again for adding this!

z

zeltak

**Comment by iqbalansari** [comment]
No worries :smile:

**Comment by zeltak** [comment]
Hi!

sorry it took me so long, had some personal and work issues to deal with :)

i installed it as you suggested but still dont see the name/subject just the mail count.

did i need to config something?

thx and sorry for the delay

Z

**Comment by iqbalansari** [comment]
Hi,

> thx and sorry for the delay

No problem :smile:

> i installed it as you suggested but still dont see the name/subject just the mail count.

It might be because you have a newer version of mu4e-alert from MELPA installed. I have updated the [release](https://github.com/iqbalansari/mu4e-alert/releases/tag/0.2.1-pre), download the `mu4e-alert-20151226.1.el` and install it using the instructions mentioned in the previous comment. 

Could you please try and report back

Thanks

**Comment by iqbalansari** [comment]
@zeltak Any update?

**Comment by zeltak** [comment]
Hi, again sorry for the delay (personal issues..)

Anyway good news it works! i installed the release download you pasted and i get the notifications with the correct sender in them..a nice new years present!

thx again, let me know if you need any more testing

best

Z

**Comment by iqbalansari** [comment]
Great, thanks for testing. I have merged this to master. You should be able to update once MELPA rebuilds `mu4e-alert`.
