### ISSUE TITLE
omit unread mail in certain folders

### ISSUE THREAD

**Issue by jabranham** [iqbalansari/mu4e-alert#6]
Hi - 

First, thanks for the great package! Just what I was looking for. 

I happen to have a few (thousand) unread messages in the /[Gmail].All Mail maildir. Obviously, I don't want those showing up in the unread mail count, though. Is there some way to customize mu4e-alert to omit these? I looked through M-x customize-group and didn't find anything.

Thanks in advance.

**Comment by iqbalansari** [comment]
Glad you found the package useful. You can customize the variable `mu4e-alert-interesting-mail-query`, in your case you can set it to something like `flag:unread AND NOT flag:trashed AND NOT maildir:"/[Gmail].All Mail"`. Hope that helps

**Comment by jabranham** [comment]
Hmm... I added this: 

```
  (setq mu4e-alert-interesting-mail-query 
        (concat
         "flag:unread"
         " AND NOT flag:trashed"
         " AND NOT maildir:"
         "[Gmail]/All Mail"))
```

to my dotemacs file, but that doesn't seem to fix the issue. Do you think it has something to do with there being a space in the All Mail directory?

**Comment by iqbalansari** [comment]
> Do you think it has something to do with there being a space in the All Mail directory? 

Yes I am pretty sure the space is the issue, try the following

```
(setq mu4e-alert-interesting-mail-query 
      (concat
       "flag:unread"
       " AND NOT flag:trashed"
       " AND NOT maildir:"
       "\"[Gmail]/All Mail\""))
```

Please note the escaped `"` around `[Gmail]/All Mail`

**Comment by jabranham** [comment]
Ah, that fixed it. Thanks for the help! If you want me to write up this and put it into the documentation, let me know and I'll submit it as a PR.

Thanks again!

**Comment by jabranham** [comment]
Oh, I spoke too soon. Unread messages in /[Gmail].All Mail are still showing up as an alert.

**Comment by iqbalansari** [comment]
> Thanks for the help! 

The pleasure is mine :smile:

> If you want me to write up this and put it into the documentation, let me know and I'll submit it as a PR.

Actually the option is documented in the [README](https://github.com/iqbalansari/mu4e-alert#general-options) but as is evident from this issue, I think an update to the documentation would be helpful. 

So yes I would appreciate a PR to improve the documentation.

**Comment by iqbalansari** [comment]
Is that a is dot in the folder name `/[Gmail].All Mail` (after the `]`)? If yes you need to update the `mu4e-alert-interesting-mail-query` to the following

```
(setq mu4e-alert-interesting-mail-query 
      (concat
       "flag:unread"
       " AND NOT flag:trashed"
       " AND NOT maildir:"
       "\"[Gmail].All Mail\""))
```

**Comment by jabranham** [comment]
Yes, I just found it as well. It also seems to require the `/` before [Gmail]. So this works: 

```
 (concat
         "flag:unread"
         " AND NOT flag:trashed"
         " AND NOT maildir:"
         "\"/[Gmail].All Mail\"")
```

**Comment by iqbalansari** [comment]
>  It also seems to require the / before [Gmail]

Oops, good catch, not sure how missed that. Really happy that you got it working.

**Comment by ReneFroger** [comment]
Thanks for the tips, iqbalansari. Very useful for me, in order to disable alerts from my spam folder in Gmail. I really love the mode line icon for mu4e-alerts. Thanks for sharing it with us!

**Comment by iqbalansari** [comment]
@ReneFroger you are welcome, I am really am happy that people are finding this package useful.
